name: Build

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          NODE_VERSION: 12.x
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v1
        with:
          node-version: $NODE_VERSION
      - run: npm install -g yarn
      - name: Run Build
        run: |
          yarn
          yarn build
