name: Build

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Use Yarn with Cache
        run: yarn --frozen-lockfile

      - name: Run Build
        run: yarn build
