name: Deploy

on:
  repository_dispatch:
    types: [deploy-event]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Env Variables
        uses: allenevans/set-env@v1.1.0
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Set STAGING for deploy
        if: github.ref == 'refs/heads/develop'
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME-stage.git

      - name: Set PRODUCTION for deploy
        if: github.ref == 'refs/heads/master'
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

      - name: Deploy to Heroku
        run: git push heroku HEAD:master -f
