name: Migrations

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  run-migrations:
    name: Run Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Set Env Variables
        uses: allenevans/set-env@v1.1.0
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'

      - name: Run Migrations Development
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        run: |
          DATABASE_URL=$(heroku config:get DATABASE_URL -a $HEROKU_APP_NAME-dev) yarn migration:run

      - name: Run Migrations Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          DATABASE_URL=$(heroku config:get DATABASE_URL -a $HEROKU_APP_NAME-stage) yarn migration:run

      - name: Run Migrations Production
        if: github.ref == 'refs/heads/master'
        run: |
          DATABASE_URL=$(heroku config:get DATABASE_URL -a $HEROKU_APP_NAME) yarn migration:run

      - name: Clean Development DB
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        run: |
          DATABASE_URL=$(heroku config:get DATABASE_URL -a $HEROKU_APP_NAME-dev) yarn db:clean

      - name: Dispatch Event For Deploy
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: deploy-event
