name: Test API

on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        env:
          NODE_VERSION: 12.x
        with:
          node-version: $NODE_VERSION
      - run: npm install -g yarn
      - name: Run Tests
        run: |
          yarn
          yarn test
